### ISSUE TITLE
SME review comments

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/guide-microprofile-telemetry-jaeger#12]
## Quick fixes

In this text: 

> To further control and customize traces, you inject a custom `Tracer` object to create and customize spans.

Remove the word "custom".

Make fields in `InventoryManager` and `InventoryResource` private. As a best practise, fields should be declared `private` unless they should be accessible from outside the class. This includes fields where you're doing CDI injection. 

In the **Injecting a custom Tracer object** section, should the call to `manager.get(hostname);` be inside the `try` block? I.e.

```java
    public Response getPropertiesForHost(@PathParam("hostname") String hostname) {
        Span getPropertiesSpan = tracer.spanBuilder("GettingProperties").startSpan();
        Properties props;
        try (Scope scope = getPropertiesSpan.makeCurrent()) {
            props = manager.get(hostname);
            if (props == null) {
                getPropertiesSpan.addEvent("Cannot get properties");
                return Response.status(Response.Status.NOT_FOUND)
                         .entity("{ \"error\" : \"Unknown hostname or the system "
                               + "service may not be running on " + hostname + "\" }")
                         .build();
            }
            getPropertiesSpan.addEvent("Received properties");
            manager.add(hostname, props);
        } finally {
            getPropertiesSpan.end();
        }
        return Response.ok(props).build();
    }
```

_If it's within the block, then the HTTP GET span will be a child of the "Getting Properties" span like this: 
![image](https://github.com/OpenLiberty/draft-guide-microprofile-telemetry-jaeger/assets/2011102/8119ed29-51c0-4a74-8652-819a2b8b3554)
 Compare with this from the current guide: 
![image](https://github.com/OpenLiberty/draft-guide-microprofile-telemetry-jaeger/assets/2011102/e34c2e0e-f94f-432d-aa15-d3df135ef486)_

In the **Enabling Telemetry implementation** section, the inventory server.xml has the comment `<!-- enable visibility to third party apis -->`, but we don't do that until much later in the guide.

## Further suggestions

_These are content questions rather than technical ones, so they're just suggestions and I leave any changes up to the guide authors._

There's quite a bit of text between adding the `@WithSpan` and `@SpanAttribute` annotations and seeing the results. When we show the resulting spans in Jaeger, should we mention using `@WithSpan` created the span and `@SpanAttribute` added the `hostname` tag?

Should we have more information about why users might want to create spans manually? (e.g. to create a span for an operation which isn't a REST request or a CDI method call, or to add additional tags (e.g. a session ID) to existing spans so you can query for them in Jaeger later)

Should we explain the difference between starting and ending a span vs. making it current and closing the scope?

I think the key points are:
 - A span isn't recorded until it's ended. You should always call `Span.end()` within a `finally` block to ensure it's always closed.
   - if you don't end the span, it won't appear in Jaeger at all
 - Making a span "current" means that it's automatically used as the parent of any new spans created on that thread (which includes both manual spans and spans created automatically by liberty). This is  usually what you want.
   - if you don't make a span "current", then new spans won't be children of it, unless you manually specify the parent
 - When you make a span "current", you need to close the `Scope` that is created
   - the `Scope` must be closed on the same thread
   - if you call `span.makeCurrent` on several different spans, the scopes must be closed in the reverse order to which they were created
   - if you always use a `try-with-resources` block, that will ensure you do both these things
   - if you forget to close a `Scope`, you may find your spans end up with the wrong parent

**Comment by gkwan-ibm** [comment]
hi @ReeceNana 

I addressed the **Quick fixes** and the first comment in the **Further suggestions**
> There's quite a bit of text between adding the @WithSpan and @SpanAttribute annotations and seeing the results. When we show the resulting spans in Jaeger, should we mention using @WithSpan created the span and @SpanAttribute added the hostname tag?

The draft site and the branch are updated.

Would you address the other comments in the **Further suggestions**?

**Comment by gkwan-ibm** [comment]
close
- all comments were addressed

**Comment by gkwan-ibm** [comment]
guide issue - https://github.com/OpenLiberty/guides-common/issues/888
