### ISSUE TITLE
Laura's review

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-telemetry-jaeger#14]
In reasonably good shape already though needs more explanation rather than just instruction.

I've not done an ID review. Some of the paragraphs could do with tidying up for grammar/punctuation so needs a writer on it still.

### Intro

- [x]  "DevOps teams" - would just "teams" work ok? The "DevOps" bit seems a bit distracting, both visually and because there's a whole range of how teams are set up and labelled. Ultimately it's the monitoring of the app that's important rather than the team who does it.

### What you'll learn

- [x]  "difficultly" - typo
- [x] "may increase" -> "can increase" - it's more concrete
- [x] The sentences defining traces, spans, and context could do with being clearer. It's quite difficult to piece the information/concepts together when they're written in the format of a series `<term><definition>` like this. Need to explain, rather than define, the concepts. For example, it might be easier to understand as "Traces represent requests, which can contain multiple operations, or _spans_. Each span comprises a name, time-related data, log messages, and metadata that describe what occurred during a transaction. Spans are associated with a context, which identifies the request within which the span occurred. Developers can then follow a single request between services through a potentially complex distributed system. " 
    - [x]  I assume it's necessary to even talk about "spans" rather than operations? And "contexts" rather than just say "requests"?
    - [x] "Exporters are components" - is this sentence even necessary? Exporters aren't mentioned again throughout the whole guide. More useful might be a sentence saying that "xxx sends the data about xxx to a backend service to xxx". Or something. Explain rather than define the concepts.
    - [x] #20
- [x] How's Jaeger relevant to all this? Needs a brief sentence saying what Jaeger contributes to the scenario, eg "Jaeger exports the data to...xxx".

### Additional prereqs

- [x] Remove ". Jaeger can be found" and collapse the two halves sentences together.

### Try what you'll build

- [x] Remove "you need to" So it just reads "wait a little longer and refresh the page to see the application services." - more concise and direct.
- [x] "You’ll see the result as the following" - don't say "the following" - instead say something like "the service details" or whatever it is that the image is showing.

### Building the app

- [x] It's not "in development mode, known as dev mode, ", it's just "in dev mode" - that's its name. There's not a mode called "development mode".

### Enabling Telemetry implementation

- [x] Instructions like "Replace the server.xml file of the system service." should end with a colon (:) to show that the code (the file path in this case) following the instruction is part of the instruction and that that's how you implement the instruction.
- [x] The text following the code box should be explaining what the previous instruction achieves (what has been changed by completing the instruction), not repeat the instruction (which is confusing). So "Enable mpTelemetry feature in the server.xml of the system service." should say something more like "The server.xml now enables the mpTelemetry feature in the system service". Similarly "Specify the otel.service.name property with the system service name and set the otel.sdk.disabled property with false to enable tracing." should be something like "The MicroProfile properties file specifies the otel.service.name property with the system service name and sets the otel.sdk.disabled property with false to enable tracing." 
- [x] If this style is copied from other guides, can you raise issues to fix the other guides too, pls? (see the REST-intro guide as an example). The whole point of the text following the instruction is to provide explanation/learning, not to just expect the user to blindly follow the instructions.

### Enabling OpenTelemetry APIs

- [x] "The MicroProfile Telemetry feature has been enabled tracing of all REST endpoints by default in the previous section." - this doesn't quite make sense. Should it say "...enabled to trace all REST endpoints..."? Or something else?

### Injecting a custom Tracer object

- [x] Again, needs to be explanatory not instructional after the instruction to create/replace a file. eg "To access the Tracer, inject it into a bean by using the @Inject annotation from the Contexts and Dependency Injections API." should be "The @Inject annotation from ...injects the Tracer into a bean...in order to/so that..." (or whatever exactly happens and what benefit it has).
- [x] "Before the InventoryManager to call the system service, create and start a span called GettingProperties by using the spanBuilder() and startSpan() Tracer APIs." - this sounds like you're asking them to do something else but I think replacing the class file has already completed the instruction. Instead it should be something like "Before the InventoryManager calls the system service, the spanBuild() and startSpan() Tracer APIs create and start a span called GettingProperties." Explain what's happening now that the file has been created.

### Testing the app

- [x] "No automated tests are provided to verify the correctness of the traces." - is this something that you might do in reality? If so, why aren't we? If it doesn't make sense in reality to test this in an app, I think just drop this sentence (I'm not sure what it adds - esp as it doesn't say why) and just have the next sentence which tells you how to check manually.

**Comment by gkwan-ibm** [comment]
Hi @ReeceNana 

I addressed the checked comments. The draft site and the branch are updated. Would you address the other comments?

**Comment by gkwan-ibm** [comment]
hi @lauracowen 

Regarding the "development mode", all guides use that term that was suggested by ID long time ago.

**Comment by lauracowen** [comment]
Re "development mode", it's been fixed in the OL docs but must not have been picked up in the guides at the same time. See https://openliberty.io/docs/latest/development-mode.html

**Comment by gkwan-ibm** [comment]
close
- all comments should be addressed

**Comment by gkwan-ibm** [comment]
guide issue - https://github.com/OpenLiberty/guides-common/issues/888
