### ISSUE TITLE
Final end-to-end test for cloud-hosted

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-telemetry-jaeger#32]
- [x] make sure to use the `draft-guide-microprofile-telemetry-jaeger` when clone
- [x] Read through the guide to check its appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on SNL
    - [x] ensure all URLs work and open new tab
    - [x] follow the instructions in the guide to test end-to-end
        - Use the `>` and `copy` buttons instead of typing

**Comment by shin19991207** [comment]
Ran guide end-to-end on SNL with `Cloud IDE with Docker (1.0)`, no issue.

**Comment by gkwan-ibm** [comment]
guide issue - https://github.com/OpenLiberty/guides-common/issues/888
