### ISSUE TITLE
Peer Review for Mac

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-telemetry-jaeger#5]
Review and test this guide by a peer member with the following prespectives
 -  by Safari
 
 README
 ---
 - [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
 - [ ] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
 - [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
 - [x] Check the appearance of the guide:
    - [x] Table of contents
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links (shoud open a new tab)
    - [x] hotspots (should highlight the code correctly)
 - [x] Check that the `pom.xml`, `server.xml`, and java files etc files are clean on the right code pane
    - [x] Remove any dependencies and features that are not required
    - [x] Ensure that the parent pom.xml files do not contain any dependencies, and all dependencies are specified in the children pom.xml files
    - [x] lines are not too long and wrapped
    - [x] lines are aligned nicely
 - [x] Examples with the right outcomes are provided
 - [x] Examples with the wrong outcomes, if any, are provided
 - [ ] Run Acrolinx Checker (above 70 score approximately)
 
 `pom.xml`
 ---
 - [x] Check that the file follows the template found here: https://github.com/OpenLiberty/draft-guides-template/blob/draft/finish/pom.xml
 - [x] Check that the dependencies and plugins are latest in all of the `pom.xml` files:
    - jakarta.jakartaee-api
    - microprofile
    - liberty-maven-plugin
    - etc.
 - [x] Check that there are 4 spaces per indent for proper formatting
 - [x] Check that no tab characters are used
 
 Overall checks:
 ---
 - [x] Check the consistency of guide with the template and other guides
 - [x] Check the quality of code according to the best coding practices
 - [x] Check that all licensing statements are properly stated in all files, with the correct year (Should be present in all Java files + the `index.html`)
 - [x] Check that the directories are properly structured
 - [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Jakarta EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/guides-common/blob/master/guide_tags.json).
 - [x] Check the `attribution` statement is accurate for the guide
 - [x] Verify the GitHub Actions scripts, if any, are accurate and consistent with other guides
 
 Additional tests:
 ---
 - [ ] tests where applicable:
    - [ ] Define test coverage and review with team (including guide contributor, if available)
    - [ ] Define detail test cases
    - [ ] Consider corner cases targeting the specific guide
    - [ ] Consider corner cases UI tests
    - [ ] Consider testing the `curl` command for localhost URLs
    - [ ] Make sure the `index.html` information is correct by visiting the root, e.g. `http://localhost:9080`
 - [ ] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
    - import the finish directory and see any complication error, unused import packages, etc
 - [x] Consider SEO title and description for the guides
 - [x] Ensure automated tests with GitHub Actions are enabled
 - [ ] Run `diff -r start/ finish/` and there is no differences expect `tag` and `end` comments 
 - [ ] Ensure that the automation tests are able to run when PR is created
 - [x] Test the guide end-to-end with working instruction and sample code with either of the following Java
    - [x] Java 11
    - [ ] Java 17
 - [x] Perform all the defined test cases

**Comment by shin19991207** [comment]
## Enabling OpenTelemetry APIs
- ```
  ... set the `+third-party` value to the [hotspot]`apiTypeVisibility` attribute in the [hotspot]`classLoader` configuration. This configuration adds `third-party`....
  ```
  [hotspot]`apiTypeVisibility` and [hotspot]`classLoader` should not highlight the comment `<!-- enable visibility to third party apis -->`

## Enabling tracing in Jakarta CDI beans
 - ```
    Annotate the [hotspot]`add()` and [hotspot]`list()` methods with the @WithSpan annotation. You can annotate the host parameter with the @SpanAttribute annotation with a customized value to indicate that it is part of the trace.
   ```
   - [hotspot]`add()` and [hotspot]`list()` should highlight the whole method instead, e.g. highlight the following code block for [hotspot]`add()`:
      ```
      public void add(@SpanAttribute(value = "hostname") String host,
                    Properties systemProps) {
        Properties props = new Properties();
        props.setProperty("os.name", systemProps.getProperty("os.name"));
        props.setProperty("user.name", systemProps.getProperty("user.name"));
        SystemData system = new SystemData(host, props);
        if (!systems.contains(system)) {
            systems.add(system);
        }
      }
     ```
   - hotspot `@WithSpan` with the code line `@WithSpan`
   - hotspot `@SpanAttribute`

## pom.xml
- update `'iberty-maven-plugin` to the latest 3.8.1 - https://github.com/OpenLiberty/ci.maven/releases/tag/liberty-maven-3.8.1

**Comment by shin19991207** [comment]
LGTM

**Comment by gkwan-ibm** [comment]
close
- review completed

**Comment by gkwan-ibm** [comment]
guide issue - https://github.com/OpenLiberty/guides-common/issues/888
