### ISSUE TITLE
Peer Review for Linux

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-telemetry-jaeger#6]
Review and test this guide by a peer member with the following prespectives
 -  by Firefox
 
 README
 ---
 - [ ] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
 - [ ] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
 - [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
 - [x] Check the appearance of the guide:
    - [x] Table of contents
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links (shoud open a new tab)
    - [x] hotspots (should highlight the code correctly)
 - [x] Check that the `pom.xml`, `server.xml`, and java files etc files are clean on the right code pane
    - [x] Remove any dependencies and features that are not required
    - [x] Ensure that the parent pom.xml files do not contain any dependencies, and all dependencies are specified in the children pom.xml files
    - [x] lines are not too long and wrapped
    - [x] lines are aligned nicely
 - [x] Examples with the right outcomes are provided
 - [ ] Examples with the wrong outcomes, if any, are provided
 - [ ] Run Acrolinx Checker (above 70 score approximately)
 
 `pom.xml`
 ---
 - [x] Check that the file follows the template found here: https://github.com/OpenLiberty/draft-guides-template/blob/draft/finish/pom.xml
 - [x] Check that the dependencies and plugins are latest in all of the `pom.xml` files:
    - jakarta.jakartaee-api
    - microprofile
    - liberty-maven-plugin
    - etc.
 - [x] Check that there are 4 spaces per indent for proper formatting
 - [x] Check that no tab characters are used
 
 Overall checks:
 ---
 - [x] Check the consistency of guide with the template and other guides
 - [x] Check the quality of code according to the best coding practices
 - [x] Check that all licensing statements are properly stated in all files, with the correct year (Should be present in all Java files + the `index.html`)
 - [x] Check that the directories are properly structured
 - [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Jakarta EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/guides-common/blob/master/guide_tags.json).
 - [x] Check the `attribution` statement is accurate for the guide
 - [x] Verify the GitHub Actions scripts, if any, are accurate and consistent with other guides
 
 Additional tests:
 ---
 - [ ] tests where applicable:
    - [ ] Define test coverage and review with team (including guide contributor, if available)
    - [ ] Define detail test cases
    - [ ] Consider corner cases targeting the specific guide
    - [ ] Consider corner cases UI tests
    - [ ] Consider testing the `curl` command for localhost URLs
    - [ ] Make sure the `index.html` information is correct by visiting the root, e.g. `http://localhost:9080`
 - [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
    - import the finish directory and see any complication error, unused import packages, etc
 - [ ] Consider SEO title and description for the guides
 - [ ] Ensure automated tests with GitHub Actions are enabled
 - [x] Run `diff -r start/ finish/` and there is no differences expect `tag` and `end` comments 
 - [ ] Ensure that the automation tests are able to run when PR is created
 - [x] Test the guide end-to-end with working instruction and sample code with either of the following Java
    - [x] Java 11
    - [x] Java 17
 - [x] Perform all the defined test cases

**Comment by Ruilin-Ma** [comment]
## microprofile-config.properties && microprofile-config.properties
```
otel.service.name=system
otel.sdk.disabled=false
# linux only
otel.traces.exporter=jaeger
# linux only
```
While running with Linux, the MicroProfile configuration files in both the /system and /inventory should include the line 'otel.traces.exporter=jaeger' to indicate that the exporter is Jaeger. An error occurred when running with the original configuration file: '- Failed to export spans. The request could not be executed. The full error message is: Failed to connect to localhost/127.0.0.1:4317.'

For the exporter setting, please refer to: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#jaeger-exporter.

**Comment by gkwan-ibm** [comment]
hi @Ruilin-Ma which version of Jaeger you used? At the Additional prerequisites section, the guide suggests to use 1.46. There is no need to specify the `otel.traces.exporter` property if use 1.46+

**Comment by ReeceNana** [comment]
Tested guide on Linux VM. Ran guide end-to-end, no failures.

- Used docker all-in-one for jaeger client 
- All tests passed.
- All outputs as expected.

**Comment by gkwan-ibm** [comment]
guide issue - https://github.com/OpenLiberty/guides-common/issues/888
