### ISSUE TITLE
Final end-to-end test

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-telemetry-jaeger#8]
- [x] Clear the `.m2` repository before running the tests
 - [x] Clone the repository with the `draft` branch
 - [x] Run `diff -r start/ finish/` and there is no differences except`tag` and `end` comments and the replace files in the readme.adoc 
 - [x] Read through the guide to check its appearance (contents, headings, paragraphs, code snippets, outputs, links, hotspots) of the guide on draft site
    - [x] ensure all hotspots work
    - [x] ensure all URLs work and open new tab
    - [x] follow the instructions in the guide to test end-to-end
        - Use the `copy` buttons instead of typing

**Comment by gkwan-ibm** [comment]
The license in the InventoryApplication.java is not right under the start directory.

![Screenshot 2023-07-26 at 11 57 54 AM](https://github.com/OpenLiberty/draft-guide-microprofile-telemetry-jaeger/assets/29576299/0501a7f1-7cea-495b-be33-a367c42ae718)

**Comment by gkwan-ibm** [comment]
SystemClient class under the start directory is not right
```
<  * Copyright (c) 2022, 2023 IBM Corporation and others.
---
>  * Copyright (c) 2023 IBM Corporation and others.
4c5
<  * are made available under the terms of the Eclipse Public License v1.0
---
>  * are made available under the terms of the Eclipse Public License 2.0
6c7
<  * http://www.eclipse.org/legal/epl-v10.html
---
>  * http://www.eclipse.org/legal/epl-2.0/
8,9c9
<  * Contributors:
<  *     IBM Corporation - Initial implementation
---
>  * SPDX-License-Identifier: EPL-2.0
10a11
```

**Comment by saumyapandyaa** [comment]
Ran guide end-to-end, no issues

**Comment by gkwan-ibm** [comment]
guide issue - https://github.com/OpenLiberty/guides-common/issues/888
